# Generated by Django 5.2.6 on 2025-12-01 14:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('disponible', models.BooleanField(default=True)),
<<<<<<< HEAD
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='libros', to='gestion.autor')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamos', models.DateField(default=django.utils.timezone.now)),
                ('fecha_max', models.DateField()),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='gestion.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to=settings.AUTH_USER_MODEL)),
=======
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Libros', to='gestion.autor')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamos', models.DateField(default=django.utils.timezone.now)),
                ('fecha_maxima', models.DateField()),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Prestamos', to='gestion.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Prestamos', to=settings.AUTH_USER_MODEL)),
>>>>>>> 1ff34db8ae80ff69bb1af0619381edf623b73fc6
            ],
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('r', 'retraso'), ('p', 'perdida'), ('d', 'deterioro')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('pagada', models.BooleanField(default=False)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
<<<<<<< HEAD
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='multas', to='gestion.prestamo')),
=======
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Multa', to='gestion.prestamos')),
>>>>>>> 1ff34db8ae80ff69bb1af0619381edf623b73fc6
            ],
        ),
    ]
